name: MaintainableCSS - an approach to writing modular, scalable and maintainable CSS | By Adam Silver
markdown: kramdown
url: http://maintainablecss.com
include: ['_pages']
collections:
  chapters:
    output: true
    permalink: /:collection/:title/
description: MaintainableCSS is an approach to writing modular, scalable and of course, maintainable CSS.